Fix: #19 going with localStorage sync, which was not done properly
yagizhanNY/openai-chatgpt3-clone pull request #21
Opened 2023-05-11 19:12 UTC by mehul1011

Future tasks could be more cleanup on code for syncing the localStore, ie making it more modular.

and implementation of NgRx store upto date with localStore (i have to disable some of it's code for now)

please create these tasks as an improvement as required.

2023-05-12 16:01 UTC, yagizhanNY requested changes

2023-05-12 16:01 UTC, yagizhanNY commented on src/app/chat/chat-content/chat-content.component.ts
> +    // if (id) {
if these commented lines are not needed any more, please delete it.

2023-05-12 16:01 UTC, yagizhanNY commented on src/app/chat/chat-content/chat-content.component.ts
> +    // this.store.dispatch(updateChatDataAction({ newChatMessage: message }));
if these commented lines are not needed any more, please delete it.

2023-05-12 16:01 UTC, yagizhanNY commented on src/app/chat/chat-content/chat-content.component.ts
> +      // this.store.dispatch(
if these commented lines are not needed any more, please delete it.

2023-05-12 16:01 UTC, yagizhanNY commented on src/app/sidebar/sidebar.component.ts
> +      // for (let i = 0; i < data?.length; i++) {
if these commented lines are not needed any more, please delete it.

2023-05-12 16:08 UTC, mehul1011 commented on src/app/chat/chat-content/chat-content.component.ts
> +    // if (id) {
For state management i need those later on. Is it fine to keep it, maybe we can have an issue as a reminder for deleting later.

Let me know in any case, i can keep it in my local and push in the branch without it.

2023-05-12 17:41 UTC, mehul1011 commented
For state management i need those later on. Is it fine to keep it, maybe we can have an issue as a reminder for deleting later.

Let me know in any case, i can keep it in my local and push in the branch without it.

2023-05-17 08:48 UTC, yagizhanNY commented
> For state management i need those later on. Is it fine to keep it, maybe we can have an issue as a reminder for deleting later.
> 
> Let me know in any case, i can keep it in my local and push in the branch without it.

Yes, it would be good if it's possible.

2023-05-26 11:51 UTC, mehul1011 commented
Hi @yagizhanNY 
I have removed it, let's merge, we can stabilize the UI

2023-05-28 09:20 UTC, yagizhanNY approved these changes

2023-05-28 09:20 UTC, merged